name: Build Jag Mail IT Image and Push to JRCC Openshift Imagestream

on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cluster Login
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL_JRCC }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD_JRCC }}"}'
          cmd: |
            'version'
      - name: Login to Openshift Docker
        run : |
          docker login ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY_JRCC }} -u ${{ secrets.OPENSHIFT4_SA_USERNAME_JRCC }} -p ${{ secrets.OPENSHIFT4_SA_PASSWORD_JRCC }}
      - name: Build the Docker image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |          
          
          docker-compose build mail-it
          
          docker tag jag-mail-it_mail-it ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY_JRCC }}/${{ secrets.OPENSHIFT4_TOOLS_NAMESPACE_JRCC }}/mail-it:latest
          docker push ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY_JRCC }}/${{ secrets.OPENSHIFT4_TOOLS_NAMESPACE_JRCC }}/mail-it:latest
